### ISSUE TITLE
有支持mac的开发环境吗？

### ISSUE THREAD

**Issue by sonwa** [Ai-Thinker-Open/Telink_825X_SDK#1]
有支持mac的开发环境吗？可以打包一个这样的开发环境工具吗？

**Comment by ospanic** [comment]
https://shyboy.oss-cn-shenzhen.aliyuncs.com/readonly/tc32-mac.zip

**Comment by ospanic** [comment]
上文中编译工具未测试过，测试过的同学可在此处留言
