### ISSUE TITLE
关于安信可uart_boot方案和泰凌OTA不相容、影响启动速度与功耗的问题

### ISSUE THREAD

**Issue by Mixiaoxiao** [Ai-Thinker-Open/Telink_825X_SDK#5]
发issuse时的commit： 3c93f1518b2da895ea2fef50eff0791cbedd5d9d

根据[TBXX_Flash_Tool](https://github.com/Ai-Thinker-Open/TBXX_Flash_Tool)中的介绍：
- TB系列模块的Flash大小为512KB
- 0x0 - 0x4000(16KB)存放的是bootloader，不可擦除。
- 0x4000 - 0x30000(176KB)存放用户固件，
- 0x30000 - 0x40000(64KB)存放Mesh配网数据，
- 0x76000-0x77000存放模组Mac地址
- 0x78000-0x79000存放天猫精灵三元组。

  

而泰凌SDK手册Flash分区为：
- 0x00000 - 0x20000 为 Old Firmware (128K)
- 0x20000 - 0x40000 为 OTA New bin storage Area (128K)
- 0x40000 之后略

  

以下是问题：
- 根据泰凌SDK手册OTA更新流程介绍，芯片可选两个启动地址0x00000 或 0x20000，即旧固件或新固件的起始地址，这是实现OTA的基础
- 根据[TB-01/02 固件烧录指南](https://docs.ai-thinker.com/_media/ble/docs/tb_module_uart_burn_guid_zh_v1.0.pdf)中的介绍，uart_boot实现是使用上电先运行16K的bootloader，该bootloader之后（运行模式下）拷贝Flash 0x2C000（**该地址与TBXX_Flash_Tool中提到的0x4000存放用户固件地址不一致？？**） 到内存0x0再运行

以下使用安信可模块（使用安信可uart_boot）实际测试：
- 执行过`bls_ota_clearNewFwDataArea()`代码后，reset或重新上电后模块无法启动
- 泰凌官方 OTA 方案写入固件数据（如8258_ble_remote示例），但OTA后无法正常启动

综上：

- 安信可uart_boot方案目前和泰凌OTA方案可能是不相容的
- OTA作为泰凌BLE芯片的一个feature，其重要性可能是要高于uart_boot的
- [TlsrComSwireWriter](https://github.com/pvvx/TlsrComSwireWriter)也是个使用UART为TLSR826x/825x刷固件的工具，但与bootloader无关，已经在[ATC_MiThermometer](https://github.com/atc1441/ATC_MiThermometer)中使用。
- 安信可使用的uart_boot涉及启动逻辑，本质上是两级boot，一方面冷启动速度会受影响。目前暂时不知道suspend， deepsleep retention , deepsleep 唤醒后是否也会走uart_boot逻辑，如果是，唤醒速度和功耗都将收到很大影响。

**Comment by ospanic** [comment]
-  uart_boot 与 OTA不兼容，如果使用了uart_boot 就不能使用OTA，如果要使用OTA，请使用原厂的烧录工具直接烧录固件，不要烧录uartboot

- 在suspend， deepsleep retention 时不会运行uartboot，在 deepsleep和rst时会运行uartboot 

- uartboot设计的初衷是解决原厂下载器价格昂贵的问题，设计时没有得到芯片原厂的技术支持，而且设计者水平有限，所以uartboot有很多缺陷

- 你说的TlsrComSwireWriter我们研究下，看下能不能集成到我们的烧录工具中，替换原来的方案
